[functions]
  directory = "netlify"
[build]
  command = "cd netlify && go build data-json.go && go build data-html.go"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/biblio-ai/functions"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
